export const Data = {
    "products": [
        {
            "id": 0,
            "name": "Sofa",
            "price": 155,
            "category": "Fresh Fruits",
            "image": "/images/amaz1.jpeg",
            "mrp": 180,
        },
        {
            "id": 1,
            "name": "Cushion",
            "price": 130,
            "category": "Fresh Fruits",
            "image": "/images/amaz2.jpeg",
            "mrp": 145,
        },
        {
            "id": 2,
            "name": "Chair",
            "price": 90,
            "category": "Fresh Fruits",
            "image": "/images/amaz3.jpeg",
            "mrp": 100,
        },
        {
            "id": 3,
            "name": "Table",
            "price": 100,
            "category": "Fresh Fruits",
            "image": "/images/amaz4.jpeg",
            "mrp": 120,
        },
        {
            "id": 4,
            "name": "Jeans",
            "price": 60,
            "category": "Fresh Fruits",
            "image": "/images/amaz5.webp",
            "mrp": 65,
        },
        {
            "id": 5,
            "name": "Shirt",
            "price": 50,
            "category": "Fresh Fruits",
            "image": "/images/amaz6.webp",
            "mrp": 60,
        },
        {
            "id": 6,
            "name": "Shoes",
            "price": 50,
            "category": "Fresh Vegetables",
            "image": "/images/amaz7.jpeg",
            "mrp": 60,
        },
        {
            "id": 7,
            "name": "Sandals",
            "price": 20,
            "category": "Fresh Vegetables",
            "image": "/images/amaz8.jpeg",
            "mrp": 30,
        },
        {
            "id": 8,
            "name": "Slippers",
            "price": 30,
            "category": "Fresh Vegetables",
            "image": "/images/amaz9.jpeg",
            "mrp": 50,
        },
        {
            "id": 9,
            "name": "Lamp",
            "price": 70,
            "category": "Dry Fruits",
            "image": "/images/amaz10.webp",
            "mrp": 90,
        },
        {
            "id": 10,
            "name": "Candle",
            "price": 80,
            "category": "Dry Fruits",
            "image": "/images/amaz11.webp",
            "mrp": 90,
        },
        {
            "id": 11,
            "name": "Cake",
            "price": 50,
            "category": "Dry Fruits",
            "image": "/images/amaz12.webp",
            "mrp": 55,
        }
    ]

}